(() => {
const CATS=['Vlees & vis','Maaltijden','Groente & fruit','Ontbijt & lunch','Dranken','Snacks & lekkers','Huishouden','Verzorging','Huisdieren','Overig'];
const KEYWORDS={
'Vlees & vis':['gehakt','kipfilet','kipdij','slavink','vlees','vis','kabeljauw','koolvis','zalm','worst','schnitzel','hamburger'],
'Groente & fruit':['paprika','tomaat','komkommer','sla','ui','wortel','appel','banaan','druif','kiwi','fruit','groente','avocado'],
'Ontbijt & lunch':['brood','kaas','beleg','yoghurt','kwark','cruesli','muesli','havermout','melk','jam','hagelslag','smeerkaas','vleeswaar'],
'Dranken':['cola','fanta','sinas','sap','koffie','thee','drank','water','limonade'],
'Snacks & lekkers':['chips','snoep','koek','chocolade','ijs','snack','toast'],
'Huishouden':['wasmiddel','wasverzachter','vaatwas','afwas','wc papier','keukenrol','vuilniszak','schoonmaak','allesreiniger'],
'Verzorging':['shampoo','deodorant','tandpasta','douchegel','maandverband','tampon','paracetamol'],
'Huisdieren':['katten','kattenbak','kattenvoer','brokjes','natvoer','kattensnoep']};
let mode=localStorage.getItem('hc-insight-mode')||'month';
let offset=Number(localStorage.getItem('hc-insight-offset')||0);
let receiptSource='digital';
const money=n=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const receipts=()=>JSON.parse(localStorage.getItem('hc-receipts-v1')||'[]');
const saveReceipts=x=>localStorage.setItem('hc-receipts-v1',JSON.stringify(x));
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const catFor=name=>{let n=String(name||'').toLowerCase();for(const [c,ks] of Object.entries(KEYWORDS))if(ks.some(k=>n.includes(k)))return c;return 'Maaltijden'};
function bounds(){let now=new Date(),start,end,label;if(mode==='week'){let d=new Date(now);d.setDate(d.getDate()-((d.getDay()+6)%7)+offset*7);start=new Date(d.getFullYear(),d.getMonth(),d.getDate());end=new Date(start);end.setDate(end.getDate()+7);label=`Week van ${start.toLocaleDateString('nl-NL',{day:'numeric',month:'long'})}`;}else{start=new Date(now.getFullYear(),now.getMonth()+offset,1);end=new Date(now.getFullYear(),now.getMonth()+offset+1,1);label=start.toLocaleDateString('nl-NL',{month:'long',year:'numeric'});label=label[0].toUpperCase()+label.slice(1);}return{start,end,label}}
function filtered(){let {start,end}=bounds();return receipts().filter(r=>{let d=new Date(r.date+'T12:00:00');return d>=start&&d<end})}
function totals(rs){let by=Object.fromEntries(CATS.map(c=>[c,0]));rs.forEach(r=>(r.lines||[]).forEach(l=>by[CATS.includes(l.category)?l.category:'Overig']+=(+l.price||0)));return by}
function render(){const c=document.querySelector('#content');if(!c)return;let rs=filtered(),by=totals(rs),sum=rs.reduce((a,r)=>a+(+r.total||0),0),budget=Number(localStorage.getItem(mode==='week'?'hc-budget-week':'hc-budget-month')||0),diff=budget?budget-sum:null,{label}=bounds();let rows=CATS.map(cat=>`<button class="insight-cat" data-cat="${esc(cat)}"><span>${esc(cat)}</span><span><strong>${money(by[cat])}</strong><small>${sum?Math.round(by[cat]/sum*100):0}%</small></span></button>`).join('');let recent=[...rs].sort((a,b)=>b.date.localeCompare(a.date)).map(r=>`<button class="receipt-row" data-id="${esc(r.id)}"><span><strong>${new Date(r.date+'T12:00:00').toLocaleDateString('nl-NL',{day:'numeric',month:'long'})} · ${esc(r.store)}</strong><small>${(r.lines||[]).length} producten${r.fileName?' · bonbestand':''}</small></span><strong>${money(r.total)}</strong></button>`).join('')||'<div class="empty">Nog geen bonnen in deze periode.</div>';
c.innerHTML=`<div class="insight-head"><div class="period-switch"><button data-mode="week" class="${mode==='week'?'active':''}">Week</button><button data-mode="month" class="${mode==='month'?'active':''}">Maand</button></div><div class="period-nav"><button data-shift="-1">‹</button><strong>${label}</strong><button data-shift="1" ${offset>=0?'disabled':''}>›</button></div></div><section class="insight-total"><small>Besteed</small><div>${money(sum)}</div><label>Budget <input id="insightBudget" inputmode="decimal" value="${budget?String(budget).replace('.',','):''}" placeholder="niet ingesteld"></label>${budget?`<p>Verschil ${diff>=0?'+ ':''}${money(diff)}</p>`:''}<small>${rs.length} ${rs.length===1?'aankoop':'aankopen'}</small></section><section class="insight-section"><h2>Verdeling</h2>${rows}</section><section class="insight-section"><h2>Aankopen</h2>${recent}</section>`;
c.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;offset=0;localStorage.setItem('hc-insight-mode',mode);localStorage.setItem('hc-insight-offset','0');render()});c.querySelectorAll('[data-shift]').forEach(b=>b.onclick=()=>{offset+=Number(b.dataset.shift);localStorage.setItem('hc-insight-offset',offset);render()});let bi=c.querySelector('#insightBudget');bi.onchange=()=>{let v=parseFloat(bi.value.replace(',','.'))||0;localStorage.setItem(mode==='week'?'hc-budget-week':'hc-budget-month',v);render()};c.querySelectorAll('.insight-cat').forEach(b=>b.onclick=()=>showCategory(b.dataset.cat,rs));c.querySelectorAll('.receipt-row').forEach(b=>b.onclick=()=>openModal(receipts().find(r=>String(r.id)===b.dataset.id)));}
function showCategory(cat,rs){let lines=[];rs.forEach(r=>(r.lines||[]).filter(l=>l.category===cat).forEach(l=>lines.push({...l,date:r.date,store:r.store})));document.querySelector('#content').innerHTML=`<button class="insight-back" id="insightBack">‹ Terug</button><h1>${esc(cat)}</h1><div class="insight-products">${lines.sort((a,b)=>b.price-a.price).map(l=>`<div><span><strong>${esc(l.name)}</strong><small>${new Date(l.date+'T12:00:00').toLocaleDateString('nl-NL',{day:'numeric',month:'short'})} · ${esc(l.store)}</small></span><strong>${money(l.price)}</strong></div>`).join('')||'<div class="empty">Geen producten.</div>'}</div>`;document.querySelector('#insightBack').onclick=render}
function categoryOptions(selected=''){return CATS.map(c=>`<option value="${esc(c)}" ${c===selected?'selected':''}>${esc(c)}</option>`).join('')}
function addProductRow(line={}){const wrap=document.querySelector('#receiptProductRows');if(!wrap)return;const row=document.createElement('div');row.className='receipt-product-row';row.innerHTML=`<div class="receipt-cell receipt-cell-product"><label>Product *</label><input class="receipt-line-name" value="${esc(line.name||'')}" placeholder="Product"></div><div class="receipt-cell receipt-cell-price"><label>Bedrag *</label><input class="receipt-line-price" inputmode="decimal" value="${line.price!==undefined&&line.price!==''?esc(String(line.price).replace('.',',')):''}" placeholder="0,00"></div><div class="receipt-cell receipt-cell-cat"><label>Categorie</label><select class="receipt-line-cat">${categoryOptions(CATS.includes(line.category)?line.category:catFor(line.name||''))}</select></div><div class="receipt-cell receipt-cell-action"><label>Acties</label><button type="button" class="receipt-delete-line" aria-label="Productregel verwijderen">⌫</button></div>`;
row.querySelector('.receipt-line-name').addEventListener('blur',e=>{const sel=row.querySelector('.receipt-line-cat');if(!sel.dataset.touched)sel.value=catFor(e.target.value)});
row.querySelector('.receipt-line-cat').addEventListener('change',e=>e.target.dataset.touched='1');
row.querySelector('.receipt-delete-line').onclick=()=>row.remove();
wrap.appendChild(row)}
function setSource(source){receiptSource=source==='photo'?'photo':'digital';document.querySelectorAll('.receipt-source').forEach(b=>{const on=b.dataset.source===receiptSource;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});const input=document.querySelector('#receiptFile');if(!input)return;if(receiptSource==='photo'){input.accept='image/*';input.setAttribute('capture','environment')}else{input.accept='image/*,.pdf,application/pdf';input.removeAttribute('capture')}}
function openModal(r){const m=document.querySelector('#receiptModal');document.querySelector('#receiptTitle').textContent=r?'Bon aanpassen':'Bon toevoegen';document.querySelector('#receiptEditId').value=r?.id||'';document.querySelector('#receiptStore').value=r?.store||'';document.querySelector('#receiptDate').value=r?.date||new Date().toISOString().slice(0,10);document.querySelector('#receiptTotal').value=r?String(r.total).replace('.',','):'';document.querySelector('#receiptNote').value=r?.note||'';document.querySelector('#receiptFile').value='';m.dataset.fileName=r?.fileName||'';document.querySelector('#receiptFileName').textContent=r?.fileName||'Geen bestand gekozen';const rows=document.querySelector('#receiptProductRows');rows.innerHTML='';(r?.lines?.length?r.lines:[{}]).forEach(addProductRow);setSource(r?.source||'digital');m.classList.add('open');m.setAttribute('aria-hidden','false')}
function close(){let m=document.querySelector('#receiptModal');m.classList.remove('open');m.setAttribute('aria-hidden','true')}
function collectLines(){return [...document.querySelectorAll('.receipt-product-row')].map(row=>{const name=row.querySelector('.receipt-line-name').value.trim(),price=parseFloat(row.querySelector('.receipt-line-price').value.replace(',','.'))||0,category=row.querySelector('.receipt-line-cat').value||catFor(name);return{name,price,category}}).filter(l=>l.name)}
window.renderInsight=render;window.openReceiptModal=()=>openModal();
window.addEventListener('DOMContentLoaded',()=>{let form=document.querySelector('#receiptForm');if(!form)return;document.querySelector('#receiptCancel').onclick=close;document.querySelector('#receiptBack').onclick=close;document.querySelector('#receiptModal').onclick=e=>{if(e.target.id==='receiptModal')close()};document.querySelectorAll('.receipt-source').forEach(b=>b.onclick=()=>setSource(b.dataset.source));document.querySelector('#receiptAddLine').onclick=()=>addProductRow({});document.querySelector('#receiptFile').onchange=e=>{const file=e.target.files[0];document.querySelector('#receiptFileName').textContent=file?.name||document.querySelector('#receiptModal').dataset.fileName||'Geen bestand gekozen'};form.onsubmit=e=>{e.preventDefault();let all=receipts(),id=document.querySelector('#receiptEditId').value||String(Date.now()),lines=collectLines(),entered=parseFloat(document.querySelector('#receiptTotal').value.replace(',','.')),total=Number.isFinite(entered)?entered:lines.reduce((a,l)=>a+l.price,0),file=document.querySelector('#receiptFile').files[0],old=all.find(r=>String(r.id)===String(id)),obj={id,store:document.querySelector('#receiptStore').value.trim(),date:document.querySelector('#receiptDate').value,total,lines,note:document.querySelector('#receiptNote').value.trim(),source:receiptSource,fileName:file?.name||document.querySelector('#receiptModal').dataset.fileName||old?.fileName||''};let i=all.findIndex(r=>String(r.id)===String(id));if(i>=0)all[i]=obj;else all.push(obj);saveReceipts(all);close();render()};});
})();
