import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import {getAuth,GoogleAuthProvider,onAuthStateChanged,signInWithPopup} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import {getFirestore,collection,doc,getDoc,onSnapshot,setDoc,deleteDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
const cfg={apiKey:'AIzaSyCk8GcRdAtmlGwfVu21YN_571A8KSQ-TFI',authDomain:'huize-chaos.firebaseapp.com',projectId:'huize-chaos',storageBucket:'huize-chaos.firebasestorage.app',messagingSenderId:'742691644230',appId:'1:742691644230:web:1488577640944cc3d6bb47'};
const app=initializeApp(cfg,'notes'),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();let user=null,notes=[];const $=id=>document.getElementById(id),fmt=x=>new Intl.DateTimeFormat('nl-NL',{dateStyle:'medium',timeStyle:'short'}).format(x?.toDate?x.toDate():new Date());
function render(){const q=$('search').value.trim().toLowerCase();const shown=notes.filter(n=>!q||`${n.title} ${n.body}`.toLowerCase().includes(q)).sort((a,b)=>(b.updatedAt?.seconds||0)-(a.updatedAt?.seconds||0));$('notes').innerHTML=shown.length?shown.map(n=>`<article class="note"><h2>${esc(n.title)}</h2><p>${esc(n.body)}</p><small>${n.updatedAt?fmt(n.updatedAt):''}</small><div class="note-actions"><button data-edit="${n.id}">Bewerken</button><button data-del="${n.id}">Verwijderen</button></div></article>`).join(''):'<div class="message">Nog geen notities.</div>'}
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function open(n={}){$('noteId').value=n.id||'';$('title').value=n.title||'';$('body').value=n.body||'';$('editor').showModal();setTimeout(()=>$('title').focus(),0)}
$('newNote').onclick=()=>open();$('cancel').onclick=()=>$('editor').close();$('search').oninput=render;$('notes').onclick=e=>{const ed=e.target.closest('[data-edit]'),del=e.target.closest('[data-del]');if(ed)open(notes.find(n=>n.id===ed.dataset.edit)||{});if(del&&confirm('Deze notitie verwijderen?'))deleteDoc(doc(db,'households','huize-chaos','members',user.uid,'privateNotes',del.dataset.del))};
$('form').onsubmit=async e=>{e.preventDefault();const id=$('noteId').value||crypto.randomUUID();await setDoc(doc(db,'households','huize-chaos','members',user.uid,'privateNotes',id),{title:$('title').value.trim(),body:$('body').value.trim(),updatedAt:serverTimestamp(),ownerUid:user.uid},{merge:true});$('editor').close()};
onAuthStateChanged(auth,async u=>{user=u;if(!u){$('message').innerHTML='<button id="login" class="primary">Aanmelden met Google</button>';$('login').onclick=()=>signInWithPopup(auth,provider);return}const member=await getDoc(doc(db,'households','huize-chaos','members',u.uid));if(!member.exists()||member.data().role!=='owner'){$('message').textContent='Mijn notities is privé en alleen zichtbaar voor de beheerder.';return}$('message').hidden=true;$('ownerApp').hidden=false;onSnapshot(collection(db,'households','huize-chaos','members',u.uid,'privateNotes'),snap=>{notes=snap.docs.map(d=>({id:d.id,...d.data()}));render()})});
