import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { getFirestore, doc, getDoc, onSnapshot, serverTimestamp, setDoc } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyCk8GcRdAtmlGwfVu21YN_571A8KSQ-TFI',authDomain:'huize-chaos.firebaseapp.com',projectId:'huize-chaos',storageBucket:'huize-chaos.firebasestorage.app',messagingSenderId:'742691644230',appId:'1:742691644230:web:1488577640944cc3d6bb47'};
const firebaseApp=initializeApp(firebaseConfig);const auth=getAuth(firebaseApp),db=getFirestore(firebaseApp);const recipeRef=doc(db,'households','huize-chaos','insight','recipes');const occasionRef=doc(db,'households','huize-chaos','insight','occasions');
const BASE=window.HUIZE_CHAOS_RECIPES||[];const PENDING_KEY='hc-recipe-pending-v1',CUSTOM_KEY='hc-recipe-custom-v1';
const list=document.querySelector('#list'),pendingBox=document.querySelector('#pending'),detail=document.querySelector('#detail'),search=document.querySelector('#search'),syncStatus=document.querySelector('#recipeSyncStatus');
let current=null,edited=null,cloudReady=false,applyingCloud=false,syncTimer=0,user=null,stopCloud=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const read=(k,f=[])=>{try{const v=JSON.parse(localStorage.getItem(k)||'null');return Array.isArray(v)?v:f}catch(_){return f}};const pending=()=>read(PENDING_KEY),custom=()=>read(CUSTOM_KEY);
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));const mergeById=(a,b)=>{const m=new Map();[...a,...b].forEach(x=>m.set(String(x.id),x));return [...m.values()]};
function allRecipes(){const edits=new Map();BASE.forEach(r=>{try{const x=JSON.parse(localStorage.getItem('hc_recipe_'+r.id)||'null');if(x)edits.set(String(r.id),x)}catch(_){}});return [...BASE.map(r=>edits.get(String(r.id))||r),...custom()]}
function setStatus(t){syncStatus.textContent=t}
function scheduleSync(){if(!cloudReady||applyingCloud||!user)return;clearTimeout(syncTimer);setStatus('Synchroniseren…');syncTimer=setTimeout(syncCloud,250)}
async function syncCloud(){if(!user)return;await setDoc(recipeRef,{pending:pending(),custom:custom(),updatedAt:serverTimestamp(),updatedBy:user.uid},{merge:false});setStatus('Gesynchroniseerd')}
async function initCloud(){onAuthStateChanged(auth,async u=>{user=u;if(!u){setStatus('Alleen op dit apparaat');return}try{const snap=await getDoc(recipeRef);if(snap.exists()){applyingCloud=true;const d=snap.data()||{};write(PENDING_KEY,mergeById(d.pending||[],pending()));write(CUSTOM_KEY,mergeById(d.custom||[],custom()));applyingCloud=false;renderList();}cloudReady=true;await syncCloud();stopCloud?.();stopCloud=onSnapshot(recipeRef,snap=>{if(!snap.exists()||applyingCloud)return;const d=snap.data()||{};applyingCloud=true;write(PENDING_KEY,d.pending||[]);write(CUSTOM_KEY,d.custom||[]);applyingCloud=false;renderList();setStatus('Gesynchroniseerd')},()=>setStatus('Synchronisatie niet beschikbaar'));}catch(err){console.warn(err);setStatus('Alleen op dit apparaat')}})}
function savePending(a){write(PENDING_KEY,a);renderList();scheduleSync()}function saveCustom(a){write(CUSTOM_KEY,a);renderList();scheduleSync()}
function sourceLabel(r){try{return r.sourceUrl?new URL(r.sourceUrl).hostname.replace(/^www\./,''):r.source||'Gedeeld'}catch(_){return r.source||'Gedeeld'}}
function renderList(){const q=search.value.trim().toLowerCase(),drafts=pending();pendingBox.innerHTML=drafts.length?`<section class="pending-recipes"><div class="pending-head"><h2>Te controleren</h2><span>${drafts.length}</span></div><p>Gedeelde recepten staan hier tot je ze hebt nagekeken.</p>${drafts.map(r=>`<button class="pending-recipe-card" data-pending="${esc(r.id)}"><span><strong>${esc(r.title||'Gedeeld recept')}</strong><small>${esc(sourceLabel(r))}</small></span><span>Controleren ›</span></button>`).join('')}</section>`:'';pendingBox.querySelectorAll('[data-pending]').forEach(b=>b.onclick=()=>openPending(b.dataset.pending));const a=allRecipes().filter(r=>(r.title||'').toLowerCase().includes(q)).slice(0,150);list.innerHTML=a.length?a.map(r=>`<button class="recipe-card" data-id="${esc(r.id)}"><span><strong>${esc(r.title)}</strong><small>${r.servings?esc(r.servings)+' personen':''}${r.imported?' · geïmporteerd':''}</small></span><span class="go">›</span></button>`).join(''):`<div class="empty">Geen recepten gevonden.</div>`;list.querySelectorAll('.recipe-card').forEach(b=>b.onclick=()=>openRecipe(b.dataset.id))}
function hideList(){list.classList.add('hidden');pendingBox.classList.add('hidden');search.classList.add('hidden');detail.classList.remove('hidden')}function backList(){detail.classList.add('hidden');list.classList.remove('hidden');pendingBox.classList.remove('hidden');search.classList.remove('hidden');current=null;edited=null;renderList()}
function getRecipe(id){return allRecipes().find(r=>String(r.id)===String(id))}function isCustom(id){return custom().some(r=>String(r.id)===String(id))}
function openRecipe(id){current=String(id);edited=JSON.parse(JSON.stringify(getRecipe(id)));hideList();showView('ingredients')}
function openPending(id){const r=pending().find(x=>String(x.id)===String(id));if(!r)return;current='pending:'+id;edited=JSON.parse(JSON.stringify(r));hideList();showReview()}
function ingredients(r){return `<div class="panel">${(r.ingredients||[]).length?r.ingredients.map(x=>`<div class="ing"><span class="qty">${esc(x.qty)}</span><span class="unit">${esc(x.unit)}</span><span>${esc(x.ingredient)}</span>${x.memo?`<span class="memo">${esc(x.memo)}</span>`:''}</div>`).join(''):'<div class="empty">Nog geen ingrediënten.</div>'}</div>`}
function showView(view){const r=edited;detail.innerHTML=`<div class="detail-head"><div><h2>${esc(r.title)}</h2><small>${r.servings?esc(r.servings)+' personen':''}${r.sourceUrl?` · <a href="${esc(r.sourceUrl)}" target="_blank" rel="noopener">bron</a>`:''}</small></div><div class="actions"><button class="btn" id="backList">Terug</button></div></div><div class="tabs"><button class="tab ${view==='ingredients'?'active':''}" data-v="ingredients">Ingrediënten</button><button class="tab ${view==='directions'?'active':''}" data-v="directions">Bereiding</button><button class="tab ${view==='edit'?'active':''}" data-v="edit">Wijzigen</button></div>${view==='ingredients'?ingredients(r):view==='directions'?`<div class="panel directions">${esc(r.directions||'Nog geen bereidingswijze.')}</div>`:editForm(r,false)}`;detail.querySelector('#backList').onclick=backList;detail.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showView(b.dataset.v));if(view==='edit')bindEdit(false)}
function ingredientRows(r){return (r.ingredients||[]).map((x,i)=>`<div class="edit-row ingredient-edit-row" data-row="${i}"><input data-f="qty" data-i="${i}" value="${esc(x.qty)}" placeholder="Aantal"><input data-f="unit" data-i="${i}" value="${esc(x.unit)}" placeholder="Eenheid"><input data-f="ingredient" data-i="${i}" value="${esc(x.ingredient)}" placeholder="Ingrediënt"><button type="button" class="remove-ing" data-remove="${i}" aria-label="Ingrediënt verwijderen">×</button></div>`).join('')}
function editForm(r,review){return `<div class="review-fields"><label>Titel<input id="titleEdit" value="${esc(r.title||'')}"></label><label>Personen<input id="servingsEdit" inputmode="numeric" value="${esc(r.servings||'')}"></label>${r.sourceUrl?`<label>Bron<input value="${esc(r.sourceUrl)}" readonly></label>`:''}</div><div class="edit-section open"><button type="button">Ingrediënten <span>▾</span></button><div class="edit-body"><div id="ingredientEditor">${ingredientRows(r)}</div><button type="button" class="btn add-ing" id="addIngredient">+ Ingrediënt</button></div></div><div class="edit-section open"><button type="button">Bereiding <span>▾</span></button><div class="edit-body"><textarea id="directionsEdit">${esc(r.directions||'')}</textarea></div></div><div class="actions review-actions">${review?'<button class="btn primary" id="approve">Goedkeuren</button><button class="btn" id="keepPending">Bewaren voor later</button><button class="btn danger" id="deletePending">Verwijderen</button>':'<button class="btn primary" id="save">Opslaan</button><button class="btn" id="cancel">Annuleren</button>'}</div>`}
function bindCommonEdit(){detail.querySelector('#titleEdit').oninput=e=>edited.title=e.target.value;detail.querySelector('#servingsEdit').oninput=e=>edited.servings=e.target.value;detail.querySelector('#directionsEdit').oninput=e=>edited.directions=e.target.value;detail.querySelectorAll('.edit-section>button').forEach(b=>b.onclick=()=>b.parentElement.classList.toggle('open'));detail.querySelectorAll('input[data-f]').forEach(el=>el.oninput=()=>edited.ingredients[+el.dataset.i][el.dataset.f]=el.value);detail.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{edited.ingredients.splice(+b.dataset.remove,1);showReviewOrEdit()});detail.querySelector('#addIngredient').onclick=()=>{edited.ingredients.push({qty:'',unit:'',ingredient:'',memo:''});showReviewOrEdit()}}
function showReviewOrEdit(){if(String(current).startsWith('pending:'))showReview();else showView('edit')}
function bindEdit(){bindCommonEdit();detail.querySelector('#save').onclick=()=>{if(isCustom(current)){const a=custom(),i=a.findIndex(x=>String(x.id)===String(current));a[i]={...edited,imported:true};saveCustom(a)}else{localStorage.setItem('hc_recipe_'+edited.id,JSON.stringify(edited))}showView('ingredients')};detail.querySelector('#cancel').onclick=()=>{edited=JSON.parse(JSON.stringify(getRecipe(current)));showView('ingredients')}}
function showReview(){detail.innerHTML=`<div class="detail-head"><div><div class="review-label">Te controleren</div><h2>${esc(edited.title||'Gedeeld recept')}</h2><small>${esc(sourceLabel(edited))}</small></div><div class="actions"><button class="btn" id="backList">Terug</button></div></div><div class="review-note">Controleer het recept. Je kunt dit nu doen of later op een ander apparaat.</div>${editForm(edited,true)}`;detail.querySelector('#backList').onclick=()=>{savePendingEdit();backList()};bindCommonEdit();detail.querySelector('#keepPending').onclick=()=>{savePendingEdit();backList()};detail.querySelector('#approve').onclick=approvePending;detail.querySelector('#deletePending').onclick=()=>{const id=String(current).replace('pending:','');savePending(pending().filter(x=>String(x.id)!==id));backList()}}
function savePendingEdit(){const id=String(current).replace('pending:','');const a=pending(),i=a.findIndex(x=>String(x.id)===id);if(i>=0){a[i]={...edited,id};savePending(a)}}
function approvePending(){if(!edited.title.trim()){alert('Vul eerst een titel in.');return}const id=String(current).replace('pending:',''),clean={...edited,id:'import-'+id,title:edited.title.trim(),ingredients:(edited.ingredients||[]).filter(x=>x.ingredient.trim()),status:'approved',imported:true};saveCustom([...custom(),clean]);savePending(pending().filter(x=>String(x.id)!==id));current=clean.id;edited=JSON.parse(JSON.stringify(clean));showView('ingredients')}
function parseIngredient(line){let s=String(line||'').replace(/^[-•*]\s*/,'').trim();const m=s.match(/^(\d+(?:[.,]\d+)?|[¼½¾⅓⅔⅛⅜⅝⅞])?\s*(g|gr|kg|ml|cl|dl|l|el|tl|eetlepel(?:s)?|theelepel(?:s)?|stuks?|stuk|blik(?:je)?|zak(?:je)?|teen|tenen|snuf(?:je)?)?\s*(.*)$/i);return{qty:(m?.[1]||'').replace(',','.'),unit:(m?.[2]||'').replace(/eetlepels?/i,'el').replace(/theelepels?/i,'tl'),ingredient:(m?.[3]||s).trim(),memo:''}}
function parseSharedText(payload){const raw=[payload.title,payload.text].filter(Boolean).join('\n').replace(/\r/g,'').trim(),url=payload.url||raw.match(/https?:\/\/\S+/)?.[0]||'';const lines=raw.split('\n').map(x=>x.trim()).filter(Boolean).filter(x=>!/^https?:\/\//.test(x));let title=(payload.title||lines[0]||'Gedeeld recept').replace(/https?:\/\/\S+/g,'').trim();let ingStart=lines.findIndex(x=>/^ingred/i.test(x)),dirStart=lines.findIndex(x=>/^(bereiding|bereidingswijze|werkwijze|instructies?)/i.test(x));let ingLines=[],directions='';if(ingStart>=0){const end=dirStart>ingStart?dirStart:lines.length;ingLines=lines.slice(ingStart+1,end)}if(dirStart>=0)directions=lines.slice(dirStart+1).join('\n');else if(lines.length>1&&ingStart<0)directions=lines.slice(1).join('\n');return{id:crypto.randomUUID(),title,servings:'',ingredients:ingLines.map(parseIngredient).filter(x=>x.ingredient),directions,sourceUrl:url,source:sourceFromUrl(url),status:'pending',sharedAt:new Date().toISOString()}}
function sourceFromUrl(url){try{const h=new URL(url).hostname.toLowerCase();if(h.includes('picnic'))return 'Picnic';return h.replace(/^www\./,'')}catch(_){return 'Gedeeld'}}
function findRecipeJson(value){if(!value)return null;if(Array.isArray(value)){for(const x of value){const f=findRecipeJson(x);if(f)return f}}else if(typeof value==='object'){const t=value['@type'];if(t==='Recipe'||(Array.isArray(t)&&t.includes('Recipe')))return value;if(value['@graph'])return findRecipeJson(value['@graph'])}return null}
function instructionText(v){if(Array.isArray(v))return v.map(x=>typeof x==='string'?x:(x?.text||x?.name||instructionText(x?.itemListElement))).filter(Boolean).join('\n');if(typeof v==='string')return v;return v?.text||''}
function parseYield(y){const s=Array.isArray(y)?y[0]:y;return String(s||'').match(/\d+/)?.[0]||''}
async function enrichFromUrl(draft){if(!draft.sourceUrl)return draft;try{const res=await fetch(draft.sourceUrl,{credentials:'omit'});if(!res.ok)throw new Error('HTTP '+res.status);const html=await res.text(),docu=new DOMParser().parseFromString(html,'text/html');for(const el of docu.querySelectorAll('script[type="application/ld+json"]')){try{const recipe=findRecipeJson(JSON.parse(el.textContent));if(!recipe)continue;return{...draft,title:recipe.name||draft.title,servings:parseYield(recipe.recipeYield)||draft.servings,ingredients:(recipe.recipeIngredient||[]).map(parseIngredient),directions:instructionText(recipe.recipeInstructions)||draft.directions,source:sourceFromUrl(draft.sourceUrl)}}catch(_){}}}catch(err){console.info('Receptlink kon niet rechtstreeks worden uitgelezen; bron blijft bij concept.',err)}return draft}
async function takeSharedRecipe(){const url=new URL(location.href);if(!url.searchParams.has('share-target')||!('caches'in window))return null;try{const cache=await caches.open('huize-chaos-shared-content-v1'),key=new URL('__shared-recipe__',url).href,res=await cache.match(key);if(!res)return null;await cache.delete(key);return await res.json()}catch(err){console.warn(err);return null}}
async function receiveSharedRecipe(){const payload=await takeSharedRecipe();if(!payload)return;let draft=parseSharedText(payload);draft=await enrichFromUrl(draft);savePending([...pending(),draft]);history.replaceState({},'',location.pathname+location.hash);openPending(draft.id)}
search.oninput=renderList;renderList();initCloud();receiveSharedRecipe();

// V1.3.85 - voorraad koppelen aan recepten
const STOCK_KEY='household-products-v2';
const stockRecipeButton=document.querySelector('#stockRecipeButton'),stockPicker=document.querySelector('#stockPicker');
let stockFilterIds=[];
function stockProducts(){try{return JSON.parse(localStorage.getItem(STOCK_KEY)||'[]')}catch(_){return[]}}
function relevantStock(){return stockProducts().filter(x=>x.status==='In huis' && /^(Bewaarproducten \(voorraad\)|Groente|Diepvries|Vlees\s*\/?\s*vis|Vlees|Vis)$/i.test(String(x.category||'')))}
function normFood(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\(gv\)/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\b(blik|blikje|pot|zak|pak|stuks?|verse|vers|diepvries|gekookte|gesneden)\b/g,' ').replace(/\s+/g,' ').trim().replace(/en$/,'')}
function ingredientMatchesProduct(ingredient,product){const a=normFood(ingredient),b=normFood(product.name);if(!a||!b)return false;return a.includes(b)||b.includes(a)||b.split(' ').filter(w=>w.length>3).every(w=>a.includes(w))}
function recipeStockScore(r,selected){const ingredients=r.ingredients||[];const hits=selected.filter(p=>ingredients.some(i=>ingredientMatchesProduct(i.ingredient,p))).length;const all=stockProducts().filter(p=>p.status==='In huis');const missing=ingredients.filter(i=>!all.some(p=>ingredientMatchesProduct(i.ingredient,p))).length;return{hits,missing}}
function renderStockPicker(){const a=relevantStock();stockPicker.innerHTML=`<div class="stock-picker"><h2>Kies uit je voorraad</h2><p>Bewaarproducten, groente, diepvries en vlees/vis. Kies één of meer producten.</p>${a.length?`<div class="actions stock-picker-actions"><button class="btn" id="clearStockSelection">Alles deselecteren</button></div><div class="stock-options">${a.map(x=>`<label class="stock-option"><input type="checkbox" data-stock-id="${esc(x.id)}" ${stockFilterIds.includes(String(x.id))?'checked':''}><span>${esc(x.name)} <small>${esc([x.quantity,x.unit].filter(Boolean).join(' '))}</small></span></label>`).join('')}</div><div class="actions"><button class="btn primary" id="findStockRecipes">Passende recepten zoeken</button><button class="btn" id="closeStockPicker">Sluiten</button></div>`:'<div class="empty">Geen producten uit deze groepen staan op In huis.</div>'}</div>`;stockPicker.querySelector('#closeStockPicker')?.addEventListener('click',()=>stockPicker.innerHTML='');stockPicker.querySelector('#clearStockSelection')?.addEventListener('click',()=>{stockFilterIds=[];stockPicker.querySelectorAll('[data-stock-id]').forEach(x=>x.checked=false);renderList()});stockPicker.querySelector('#findStockRecipes')?.addEventListener('click',()=>{stockFilterIds=[...stockPicker.querySelectorAll('[data-stock-id]:checked')].map(x=>x.dataset.stockId);renderList()})}
stockRecipeButton?.addEventListener('click',renderStockPicker);
const originalRenderList=renderList;
renderList=function(){if(!stockFilterIds.length)return originalRenderList();const selected=relevantStock().filter(x=>stockFilterIds.includes(String(x.id)));const q=search.value.trim().toLowerCase();const ranked=allRecipes().filter(r=>(r.title||'').toLowerCase().includes(q)).map(r=>({r,s:recipeStockScore(r,selected)})).filter(x=>x.s.hits>0).sort((a,b)=>b.s.hits-a.s.hits||a.s.missing-b.s.missing).slice(0,150);pendingBox.innerHTML='';list.innerHTML=ranked.length?ranked.map(({r,s})=>`<button class="recipe-card" data-id="${esc(r.id)}"><span><strong>${esc(r.title)}</strong><small>${r.servings?esc(r.servings)+' personen':''}</small><div class="match-label">${s.missing===0?'Alles in huis':s.missing<=1?'Bijna compleet':'Past bij voorraad'} · ${s.hits} gekozen product${s.hits===1?'':'en'}</div></span><span class="go">›</span></button>`).join(''):'<div class="empty">Geen passende recepten gevonden.</div>';list.querySelectorAll('.recipe-card').forEach(b=>b.onclick=()=>openRecipe(b.dataset.id))};
function deductionCandidates(r){const stock=stockProducts().filter(p=>p.status==='In huis');return (r.ingredients||[]).map(i=>{const p=stock.find(p=>ingredientMatchesProduct(i.ingredient,p));return p?{ingredient:i,product:p}:null}).filter(Boolean)}
function showDeduct(r){const rows=deductionCandidates(r);detail.innerHTML=`<div class="detail-head"><div><h2>Recept gemaakt</h2><small>${esc(r.title)}</small></div></div><div class="panel deduct-panel"><p>Controleer wat van de voorraad wordt afgeboekt. Pas een hoeveelheid aan als je minder of meer hebt gebruikt.</p>${rows.length?rows.map((x,i)=>`<div class="deduct-row"><span>${esc(x.product.name)}</span><input data-deduct="${i}" inputmode="decimal" value="${esc(x.ingredient.qty||'')}" aria-label="Hoeveelheid"><span>${esc(x.ingredient.unit||x.product.unit||'')}</span></div>`).join(''):'<div class="empty">Geen ingrediënten gevonden die aan je voorraad gekoppeld kunnen worden.</div>'}</div><div class="actions"><button class="btn primary" id="confirmDeduct" ${rows.length?'':'disabled'}>Bevestigen en afboeken</button><button class="btn" id="cancelDeduct">Annuleren</button></div>`;detail.querySelector('#cancelDeduct').onclick=()=>showView('ingredients');detail.querySelector('#confirmDeduct')?.addEventListener('click',()=>{const products=stockProducts();rows.forEach((row,i)=>{const p=products.find(x=>String(x.id)===String(row.product.id));if(!p)return;const used=parseFloat(String(detail.querySelector(`[data-deduct="${i}"]`).value).replace(',','.'));const have=parseFloat(String(p.quantity).replace(',','.'));if(Number.isFinite(used)&&Number.isFinite(have)){p.quantity=String(Math.max(0,have-used));if(+p.quantity===0){p.status='Niet in huis';p.shopping=false;p.done=false}}});localStorage.setItem(STOCK_KEY,JSON.stringify(products));window.dispatchEvent(new Event('huize-chaos-products-changed'));alert('Voorraad is bijgewerkt.');showView('ingredients')})}
const originalShowView=showView;
showView=function(view){originalShowView(view);if(view==='ingredients'&&edited){const panel=detail.querySelector('.panel');if(panel){const actions=document.createElement('div');actions.className='actions recipe-occasion-actions';actions.innerHTML='<button class="btn primary" id="madeRecipe">Recept gemaakt</button><button class="btn" id="addToOccasion">Toevoegen aan gelegenheid</button>';panel.insertAdjacentElement('afterend',actions);actions.querySelector('#madeRecipe').onclick=()=>showDeduct(edited);actions.querySelector('#addToOccasion').onclick=()=>showOccasionPicker(edited)}}};
const OCCASION_KEY='huize-chaos-occasions-v1';
function localOccasions(){try{return JSON.parse(localStorage.getItem(OCCASION_KEY)||'[]')}catch(_){return[]}}
function showOccasionPicker(r){const a=localOccasions();detail.insertAdjacentHTML('beforeend',`<div class="panel occasion-picker"><h3>Toevoegen aan gelegenheid</h3>${a.length?a.map(e=>`<button class="btn occasion-choice" data-occ="${esc(e.id)}">${esc(e.name)} <small>${esc(e.date||'')}</small></button>`).join(''):'<p>Nog geen gelegenheden gevonden. Maak eerst een gelegenheid aan.</p>'}</div>`);detail.querySelectorAll('[data-occ]').forEach(b=>b.onclick=()=>addCurrentRecipeToOccasion(r,b.dataset.occ))}
async function addCurrentRecipeToOccasion(r,id){const a=localOccasions(),e=a.find(x=>String(x.id)===String(id));if(!e)return;e.menu=e.menu||[];e.menu.push({type:'Hapje',dish:r.title,recipeId:String(r.id),recipeServings:r.servings||'',ingredients:(r.ingredients||[]).map(x=>({qty:x.qty||'',unit:x.unit||'',ingredient:x.ingredient||'',memo:x.memo||'',enabled:true}))});localStorage.setItem(OCCASION_KEY,JSON.stringify(a));window.dispatchEvent(new Event('huize-chaos-occasions-changed'));try{if(user)await setDoc(occasionRef,{events:a,updatedAt:serverTimestamp(),updatedBy:user.uid},{merge:false})}catch(err){console.warn('Gelegenheid is lokaal bijgewerkt; cloudsynchronisatie volgt via Gelegenheden.',err)}alert('Recept toegevoegd aan '+e.name+'. Je kunt daar kiezen welke ingrediënten je wilt gebruiken.');showView('ingredients')}



// V1.3.85 - recepten per week plannen (zonder dagen)
const RECIPE_WEEK_KEY='huize-chaos-recipe-weeks-v1';
function recipeWeekPlans(){try{return JSON.parse(localStorage.getItem(RECIPE_WEEK_KEY)||'[]')}catch(_){return[]}}
function isoWeekKey(d=new Date()){const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return `${x.getUTCFullYear()}-W${String(Math.ceil((((x-y)/86400000)+1)/7)).padStart(2,'0')}`}
function weekOptions(count=16){let d=new Date(),out=[];for(let i=0;i<count;i++){const x=new Date(d);x.setDate(x.getDate()+i*7);const k=isoWeekKey(x),n=Number(k.slice(-2));out.push(`<option value="${k}">Week ${n}</option>`)}return out.join('')}
function showWeekPlanner(r){detail.querySelector('.recipe-week-picker')?.remove();const box=document.createElement('div');box.className='panel recipe-week-picker';box.innerHTML=`<h3>Plan voor week</h3><p>Geen dag nodig. De ingrediënten verschijnen alleen op de boodschappenlijst van deze week.</p><select id="recipePlanWeek">${weekOptions()}</select><div class="actions"><button class="btn primary" id="saveRecipeWeek">Inplannen</button></div>`;detail.appendChild(box);box.querySelector('#saveRecipeWeek').onclick=()=>{const week=box.querySelector('#recipePlanWeek').value,plans=recipeWeekPlans();const existing=plans.find(x=>String(x.recipeId)===String(r.id)&&x.week===week);const plan={id:existing?.id||String(Date.now()),recipeId:String(r.id),title:r.title,week,servings:r.servings||'',ingredients:(r.ingredients||[]).map((i,n)=>({id:String(n),qty:i.qty||'',unit:i.unit||'',ingredient:i.ingredient||'',memo:i.memo||'',done:false}))};if(existing)Object.assign(existing,plan);else plans.push(plan);localStorage.setItem(RECIPE_WEEK_KEY,JSON.stringify(plans));window.dispatchEvent(new Event('huize-chaos-recipe-weeks-changed'));alert(`${r.title} staat gepland voor week ${Number(week.slice(-2))}.`);box.remove()}}
const _showViewWeek=showView;showView=function(view){_showViewWeek(view);if(view==='ingredients'&&edited){const actions=detail.querySelector('.recipe-occasion-actions');if(actions&&!actions.querySelector('#planRecipeWeek')){const b=document.createElement('button');b.className='btn';b.id='planRecipeWeek';b.textContent='Plan voor week';b.onclick=()=>showWeekPlanner(edited);actions.appendChild(b)}}};
