import{initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{getAuth,GoogleAuthProvider,onAuthStateChanged,signInWithPopup}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import{getFirestore,collection,doc,getDoc,onSnapshot,setDoc,deleteDoc,serverTimestamp,query,where}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
const cfg={apiKey:'AIzaSyCk8GcRdAtmlGwfVu21YN_571A8KSQ-TFI',authDomain:'huize-chaos.firebaseapp.com',projectId:'huize-chaos',storageBucket:'huize-chaos.firebasestorage.app',messagingSenderId:'742691644230',appId:'1:742691644230:web:1488577640944cc3d6bb47'};
const app=initializeApp(cfg,'large-purchases'),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();
const $=id=>document.getElementById(id);
// Gebruik de bestaande, al toegestane insight-collectie. Door kind=largePurchase blijven deze documenten volledig los van boodschappen.
const coll=collection(db,'households','huize-chaos','insight');
const purchaseQuery=query(coll,where('kind','==','largePurchase'));
const categoryDoc=doc(db,'households','huize-chaos','insight','largePurchaseCategories');
const DEFAULT_CATEGORIES=['Auto','Elektronica','Wonen & interieur','Apparaten','Kleding & accessoires','Gereedschap','Tuin','Hobby & vrije tijd','Overig'];
let user=null,purchases=[],categories=[...DEFAULT_CATEGORIES],current=null,pendingAttachment=null,removeExisting=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const euro=n=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const nlDate=s=>s?new Intl.DateTimeFormat('nl-NL').format(new Date(`${s}T12:00:00`)):'';
const daysUntil=s=>s?Math.ceil((new Date(`${s}T23:59:59`)-new Date())/86400000):null;
function normalizedCategories(){return [...new Set([...DEFAULT_CATEGORIES,...categories,...purchases.map(x=>x.category).filter(Boolean)])].sort((a,b)=>a.localeCompare(b,'nl'))}
function renderCategoryChoices(){
  categories=normalizedCategories();
  const select=$('category');
  const currentValue=select.value;
  select.innerHTML='<option value="">Kies categorie</option>'+categories.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');
  if(currentValue&&categories.includes(currentValue))select.value=currentValue;
  const keep=$('categoryFilter').value;
  const used=[...new Set(purchases.map(x=>x.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'nl'));
  $('categoryFilter').innerHTML='<option value="">Alle categorieën</option>'+used.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');
  $('categoryFilter').value=used.includes(keep)?keep:'';
}
function render(){renderCategoryChoices();const q=$('search').value.trim().toLowerCase(),cat=$('categoryFilter').value;let list=purchases.filter(p=>(!q||`${p.name} ${p.store} ${p.category||''} ${p.model||''} ${p.serial||''} ${p.note||''}`.toLowerCase().includes(q))&&(!cat||p.category===cat));const sort=$('sort').value;list.sort((a,b)=>sort==='date-asc'?String(a.date).localeCompare(String(b.date)):sort==='price-desc'?(Number(b.price)||0)-(Number(a.price)||0):sort==='name'?String(a.name).localeCompare(String(b.name),'nl'):String(b.date).localeCompare(String(a.date)));$('purchases').innerHTML=list.length?list.map(p=>{const d=daysUntil(p.warranty),w=p.warranty?(d<0?'Garantie verlopen':d<=60?`Garantie nog ${Math.max(0,d)} dagen`:`Garantie t/m ${nlDate(p.warranty)}`):'';return `<article class="purchase" data-id="${esc(p.id)}"><div class="purchase-main"><div><h2>${esc(p.name)}</h2><div class="meta">${nlDate(p.date)} · ${esc(p.store)}</div></div><div class="price">${euro(p.price)}</div></div><div class="chips">${p.category?`<span class="chip">${esc(p.category)}</span>`:''}${p.attachment?.data?'<span class="chip">Bon bewaard</span>':''}${w?`<span class="chip warranty ${d<=60?'warn':'ok'}">${esc(w)}</span>`:''}</div></article>`}).join(''):'<div class="empty">Nog geen aankopen gevonden.</div>'}
function resetForm(p={}){current=p.id?p:null;$('purchaseId').value=p.id||'';$('name').value=p.name||'';$('date').value=p.date||new Date().toISOString().slice(0,10);$('store').value=p.store||'';$('price').value=p.price!=null?String(p.price).replace('.',','):'';renderCategoryChoices();$('category').value=p.category||'';$('warranty').value=p.warranty||'';$('model').value=p.model||'';$('serial').value=p.serial||'';$('note').value=p.note||'';$('attachment').value='';pendingAttachment=null;removeExisting=false;$('editorTitle').textContent=p.id?'Aankoop wijzigen':'Aankoop toevoegen';showAttachment(p.attachment)}
function showAttachment(a){$('attachmentInfo').textContent=a?.data?`${a.name||'Bon'} · opgeslagen bij deze aankoop`:'Nog geen bestand gekoppeld.';$('removeAttachment').hidden=!a?.data}
function openEditor(p={},fromHistory=false){resetForm(p);if(!fromHistory)history.pushState({...history.state,hcPurchaseScreen:'editor',hcPurchaseId:p.id||''},'',location.href);if(!$('editor').open)$('editor').showModal();$('editor').setAttribute('tabindex','-1');$('editor').focus({preventScroll:true})}
function closeDialog(id){if(history.state?.hcPurchaseScreen===id){history.back();return}if($(id).open)$(id).close()}
function openDetail(p,fromHistory=false){current=p;if(!fromHistory)history.pushState({...history.state,hcPurchaseScreen:'detail',hcPurchaseId:p.id},'',location.href);const d=daysUntil(p.warranty);$('detailContent').innerHTML=`<h1>${esc(p.name)}</h1><div class="meta">${nlDate(p.date)} · ${esc(p.store)}</div><div class="detail-price">${euro(p.price)}</div><div class="detail-grid">${p.category?`<div class="detail-field"><small>Categorie</small>${esc(p.category)}</div>`:''}${p.warranty?`<div class="detail-field"><small>Garantie</small>${esc(nlDate(p.warranty))}${d<0?' · verlopen':d<=60?` · nog ${Math.max(0,d)} dagen`:''}</div>`:''}${p.model?`<div class="detail-field"><small>Merk / type</small>${esc(p.model)}</div>`:''}${p.serial?`<div class="detail-field"><small>Serienummer</small>${esc(p.serial)}</div>`:''}</div>${p.note?`<div class="note">${esc(p.note)}</div>`:''}${p.attachment?.data?`<button class="receipt-open" id="openAttachment">Bon / document openen</button>`:'<div class="message">Geen aankoopbon gekoppeld.</div>'}`;if(!$('detail').open)$('detail').showModal();$('openAttachment')?.addEventListener('click',()=>openAttachment(p.attachment))}
function openAttachment(a){if(!a?.data)return;const w=window.open();if(!w){alert('De bon kon niet worden geopend. Sta pop-ups toe voor Huize Chaos.');return}if(a.type==='application/pdf'){w.location.href=a.data}else{w.document.write(`<title>${esc(a.name||'Aankoopbon')}</title><style>body{margin:0;background:#222;display:grid;place-items:center;min-height:100vh}img{max-width:100%;height:auto}</style><img src="${a.data}">`)}}
async function imageAttachment(file){const url=URL.createObjectURL(file);const img=await new Promise((res,rej)=>{const i=new Image;i.onload=()=>res(i);i.onerror=rej;i.src=url});let scale=Math.min(1,1400/Math.max(img.naturalWidth,img.naturalHeight)),quality=.78,data='';for(let attempt=0;attempt<6;attempt++){const c=document.createElement('canvas');c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(img.naturalHeight*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);data=c.toDataURL('image/jpeg',quality);if(data.length<760000)break;scale*=.82;quality=Math.max(.5,quality-.08)}URL.revokeObjectURL(url);if(data.length>=800000)throw new Error('De foto blijft te groot. Maak een foto met een lagere resolutie.');return{name:file.name.replace(/\.[^.]+$/,'.jpg'),type:'image/jpeg',data}}
async function fileAttachment(file){if(file.type.startsWith('image/'))return imageAttachment(file);if(file.type!=='application/pdf')throw new Error('Gebruik een foto of PDF.');if(file.size>560000)throw new Error('Deze PDF is te groot om veilig mee te synchroniseren. Gebruik een foto van de bon of een PDF kleiner dan ongeveer 550 kB.');const data=await new Promise((res,rej)=>{const r=new FileReader;r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});return{name:file.name,type:file.type,data}}
async function saveCategories(){await setDoc(categoryDoc,{kind:'largePurchaseCategories',categories,updatedAt:serverTimestamp()},{merge:true})}
$('addCategory').onclick=async()=>{const name=prompt('Naam van de nieuwe categorie:')?.trim();if(!name)return;if(categories.some(c=>c.toLowerCase()===name.toLowerCase())){const existing=categories.find(c=>c.toLowerCase()===name.toLowerCase());$('category').value=existing;return}categories.push(name);categories=normalizedCategories();renderCategoryChoices();$('category').value=name;try{await saveCategories()}catch(err){console.error(err);alert('De categorie kon niet worden gesynchroniseerd, maar je kunt hem wel voor deze aankoop gebruiken.')}};
$('attachment').onchange=async e=>{const file=e.target.files[0];if(!file)return;$('attachmentInfo').textContent='Bon voorbereiden…';try{pendingAttachment=await fileAttachment(file);removeExisting=false;showAttachment(pendingAttachment)}catch(err){pendingAttachment=null;e.target.value='';$('attachmentInfo').textContent=err.message;alert(err.message)}};
$('removeAttachment').onclick=()=>{pendingAttachment=null;removeExisting=true;showAttachment(null)};$('newPurchase').onclick=()=>openEditor();$('cancel').onclick=()=>closeDialog('editor');$('backEditor').onclick=()=>closeDialog('editor');$('backDetail').onclick=()=>closeDialog('detail');$('search').oninput=render;$('categoryFilter').onchange=render;$('sort').onchange=render;$('purchases').onclick=e=>{const card=e.target.closest('[data-id]');if(card){const p=purchases.find(x=>x.id===card.dataset.id);if(p)openDetail(p)}};
$('editPurchase').onclick=()=>{const p=current;if(!p)return;if($('detail').open)$('detail').close();openEditor(p)};$('deletePurchase').onclick=async()=>{if(!current||!confirm(`Aankoop “${current.name}” verwijderen?`))return;try{await deleteDoc(doc(coll,current.id));closeDialog('detail')}catch(err){console.error(err);alert('Verwijderen is niet gelukt.')}};
$('form').onsubmit=async e=>{e.preventDefault();if(!user){alert('Je bent niet aangemeld.');return}const raw=$('price').value.trim().replace(/\./g,'').replace(',','.');const price=Number(raw);if(!Number.isFinite(price)||price<0){alert('Vul een geldig bedrag in.');return}const existingId=$('purchaseId').value;const id=existingId||`largePurchase-${crypto.randomUUID()}`,old=purchases.find(x=>x.id===id);const attachment=removeExisting?null:(pendingAttachment||old?.attachment||null);const data={kind:'largePurchase',name:$('name').value.trim(),date:$('date').value,store:$('store').value.trim(),price,category:$('category').value,warranty:$('warranty').value,model:$('model').value.trim(),serial:$('serial').value.trim(),note:$('note').value.trim(),attachment,ownerUid:user.uid,updatedAt:serverTimestamp()};try{await setDoc(doc(coll,id),data,{merge:false});closeDialog('editor')}catch(err){console.error('Aankoop opslaan mislukt:',err);const code=err?.code||'';if(code.includes('permission-denied'))alert('Opslaan is geblokkeerd door de synchronisatie-instellingen.');else if(code.includes('resource-exhausted')||String(err?.message).includes('longer than'))alert('De aankoopbon is te groot om te synchroniseren. Gebruik een kleinere foto of PDF.');else alert(`Opslaan is niet gelukt${code?` (${code})`:''}. Probeer het opnieuw.`)}};
history.replaceState({...history.state,hcPurchaseScreen:'list',hcPurchaseId:''},'',location.href);window.addEventListener('popstate',e=>{if($('editor').open)$('editor').close();if($('detail').open)$('detail').close();const s=e.state?.hcPurchaseScreen,id=e.state?.hcPurchaseId;if(s==='detail'){const p=purchases.find(x=>x.id===id);if(p)openDetail(p,true)}else if(s==='editor'){const p=purchases.find(x=>x.id===id)||{};openEditor(p,true)}});
onAuthStateChanged(auth,async u=>{user=u;if(!u){$('message').innerHTML='<button id="login" class="primary">Aanmelden met Google</button>';$('login').onclick=()=>signInWithPopup(auth,provider);$('sync').textContent='Niet aangemeld';return}try{const member=await getDoc(doc(db,'households','huize-chaos','members',u.uid));if(!member.exists()){$('message').textContent='Je hebt nog geen toegang tot Huize Chaos.';$('sync').textContent='Geen toegang';return}const catSnap=await getDoc(categoryDoc);if(catSnap.exists()&&Array.isArray(catSnap.data().categories))categories=[...DEFAULT_CATEGORIES,...catSnap.data().categories];$('message').hidden=true;$('purchaseApp').hidden=false;$('sync').textContent='Synchroniseren…';onSnapshot(purchaseQuery,snap=>{purchases=snap.docs.map(d=>({id:d.id,...d.data()}));render();$('sync').textContent='Gesynchroniseerd'},err=>{console.error(err);$('sync').textContent='Synchronisatie niet beschikbaar'})}catch(err){console.error(err);$('message').textContent='Aankopen konden niet worden geladen.'}});
